### PR TITLE
Add Kairos as default branding

### PR DESCRIPTION
**Pull request by mauromorales**
I thought, GetString value would return the default in case it wasn't given, am I missing something there?

### CODE REVIEW

**Comment by Itxaka** [comment]
It should actually return the default indeed but only if the CMD containing the flag has been initialized. Is it possible that we are calling it from a different cnd that does not init the flag?

**Comment by jimmykarily** [comment]
> I thought, GetString value would return the default in case it wasn't given, am I missing something there?

from the `*Viper.find` method doc (which is called eventually):

```
// Viper will check to see if an alias exists first.
// Viper will then check in the following order:
// flag, env, config file, key/value store.
// Lastly, if no value was found and flagDefault is true, and if the key
// corresponds to a flag, the flag's default value is returned.
```

**Comment by Itxaka** [comment]
ah yes, this is because we are setting the flags with cobra plain flag but getting them with viper without binding one to the other.

```
$ go run main.go build-uki df --keys caca
Before binding: 
After binding: Kairos
```

So we are just missing a `viper.BindPFlags(c.Flags())` after adding the flags in the `cobra.Command` and this will start working again. That just binds viper tot he Flagset so you can access it from viper directly.

**Comment by Itxaka** [comment]
```diff
diff --git a/cmd/build-uki.go b/cmd/build-uki.go
index 782d843..32434b7 100644
--- a/cmd/build-uki.go
+++ b/cmd/build-uki.go
@@ -136,6 +136,7 @@ func NewBuildUKICmd() *cobra.Command {
        c.MarkFlagRequired("keys")
        // Mark some flags as mutually exclusive
        c.MarkFlagsMutuallyExclusive([]string{"extra-cmdline", "extend-cmdline"}...)
+       viper.BindPFlags(c.Flags())
        return c
 }
```

**Comment by mauromorales** [comment]
awesome, thanks for the help guys .... let's hope that by binding them and properly having all the defaults we don't start seeing other bugs LOLOL

**Pull request merged**
